### ISSUE TITLE
Screen capturing stops on Windows after a while with error "Access denied"

### ISSUE THREAD

**Issue by arividar** [arividar/scrabber#2]
The error occurs on Windows in a realease build after running for a while:
```
[2023-03-05T09:59:08Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.08.png
[2023-03-05T09:59:19Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.18.png
[2023-03-05T09:59:29Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.29.png
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access is denied. (0x80070005)', src\lib.rs:28:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\scrabber.exe --path C:\Users\Ari\OneDrive\__TimeTrack\ -f` (exit code: 101)
```

**Comment by arividar** [comment]
The error shown in the log is like this:

```
 [2023-03-05T09:59:08Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.08.png
[2023-03-05T09:59:19Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.18.png
[2023-03-05T09:59:29Z INFO  scrabber] Wrote screenshot C:\Users\Ari\OneDrive\__TimeTrack\2023-03-05\2023-03-05T09.59.29.png
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Access is denied. (0x80070005)', src\lib.rs:28:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\scrabber.exe --path C:\Users\Ari\OneDrive\__TimeTrack\ -f` (exit code: 101)
```

**Comment by arividar** [comment]
Does not seem to occur on Mac - probably an Windows only problem.

**Comment by arividar** [comment]
Fixed in commit 8b96286. Replaced all .unwrap() calls with proper error handling and added explicit file closing with flush/sync operations to prevent Windows 'Access denied' errors.
